apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: absa-cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: absa-cloud
spec:
  replicas: 1
  # Usiamo Recreate invece di RollingUpdate perché il volume è ReadWriteOnce
  # Poiché il disco può essere montato da un solo pod alla volta, con RollingUpdate
  # il nuovo pod resterebbe bloccato in attesa che il vecchio liberi il volume.
  # Con Recreate il vecchio pod viene prima spento e poi viene avviato quello nuovo.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: absa-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-sql
          configMap:
            # creata da ansible/local/playbook.yml a partire da db/init.sql
            name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: absa-cloud
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
